// Generated by https://quicktype.io

export interface Teacher {
    TeacherID:         string;
    TeacherName:       string;
    TeacherDepartment: string;
    TeacherPicture:    string;
    favorite:          string;
}
